CREATE TABLE IF NOT EXISTS ai_news_feed (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    source VARCHAR(50) NOT NULL COMMENT '来源平台',
    source_post_id VARCHAR(128) NOT NULL COMMENT '来源帖子唯一标识',
    source_url VARCHAR(500) NOT NULL COMMENT '原文链接',
    normalized_url VARCHAR(500) DEFAULT NULL COMMENT '归一化后的链接',
    title VARCHAR(300) NOT NULL COMMENT '标题',
    author_name VARCHAR(100) DEFAULT NULL COMMENT '作者名称',
    raw_content MEDIUMTEXT COMMENT '清洗后的正文',
    content_hash VARCHAR(64) DEFAULT NULL COMMENT '内容哈希',
    event_fingerprint VARCHAR(64) DEFAULT NULL COMMENT '事件指纹',
    duplicate_of_id BIGINT DEFAULT NULL COMMENT '主记录 ID',
    raw_publish_time DATETIME DEFAULT NULL COMMENT '原始发布时间',
    summary TEXT COMMENT 'AI 摘要',
    highlight VARCHAR(500) DEFAULT NULL COMMENT '一句话爆点',
    category VARCHAR(50) DEFAULT NULL COMMENT '内容分类',
    tags VARCHAR(255) DEFAULT NULL COMMENT '标签列表',
    spicy_index TINYINT DEFAULT NULL COMMENT '吃瓜指数，1 到 10',
    verdict VARCHAR(20) NOT NULL DEFAULT 'keep' COMMENT 'AI 判定结果',
    drop_reason VARCHAR(255) DEFAULT NULL COMMENT '丢弃原因',
    ai_model VARCHAR(100) DEFAULT NULL COMMENT '模型标识',
    ai_prompt_version VARCHAR(50) DEFAULT NULL COMMENT 'Prompt 版本',
    ingest_token_name VARCHAR(50) DEFAULT NULL COMMENT '推送令牌标识',
    status VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '记录状态',
    first_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '首次抓取时间',
    last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最近抓取时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_source_post (source, source_post_id),
    KEY idx_created_at (created_at),
    KEY idx_normalized_url (normalized_url),
    KEY idx_content_hash (content_hash),
    KEY idx_event_fingerprint (event_fingerprint),
    KEY idx_duplicate_of_id (duplicate_of_id),
    KEY idx_spicy_index (spicy_index),
    KEY idx_category (category),
    KEY idx_last_seen_at (last_seen_at),
    KEY idx_status_created_at (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 资讯聚合信息流';
